name: Build LaTeX and deploy on GitHub Releases
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install nokogiri
          gem install bibtex-ruby
          # Add any other gem installations or setup commands here

      - name: Generate bibliography
        run: |
          ruby bibtex_prettifier.rb

      - name: Build latex
        uses: DanySK/compile-and-publish-all-latex@2.0.28
        with:
          token: ${{ secrets.GITHUB_TOKEN }}